title: "Welcome to holidaygirl1225's game secrets, glitches, and theories blog!"

collections:
  comments:
    output: true
    permalink: /:title/:collection

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "_comments/"
    values:
      layout: "comments"
